version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: RAILWAY_TRANSPORT_COMPANY
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - .src/main/resources/sql:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  java-app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
    ports:
      - "8080:8080"

  frontend:
    build: ../java-school-frontend
    ports:
      - "3000:3000"
    depends_on:
      - java-app
    environment:
      REACT_APP_BACKEND_URL: http://localhost:8080

  mkdocs:
    image: squidfunk/mkdocs-material
    volumes:
      - ../javaschool-doc:/docs
    ports:
      - "8000:8000"
