version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: RAILWAY_TRANSPORT_COMPANY
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  java-app:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/RAILWAY_TRANSPORT_COMPANY
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: root
    ports:
      - "8080:8080"

